### PR TITLE
v0.7

### PR DESCRIPTION
**Pull request by KlausC**
Made changes for julia v0.7 - not compatible with v0.6

### CODE REVIEW

**Comment by pbouffard** [comment]
FWIW I happened to notice that the `matrixdepot(name)` method (i.e. `matrixdepot(name::AbstractString)`) in this branch seems to be broken:

```
julia> matrixdepot("magic")
ERROR: LoadError: UndefVarError: @repl not defined
Stacktrace:
 [1] eval at ./boot.jl:319 [inlined]
 [2] eval at /Users/pat/.julia/packages/MatrixDepot/LuiY/src/MatrixDepot.jl:1 [inlined]
 [3] matrixdepot(::String) at /Users/pat/.julia/packages/MatrixDepot/LuiY/src/common.jl:126
 [4] top-level scope at none:0
in expression starting at none:1

julia> versioninfo()
Julia Version 0.7.0-beta2.0
Commit b145832402* (2018-07-13 19:54 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

**Comment by KlausC** [comment]
@pbouffard 
Maybe you can see, that this PR has not been merged by the package owners.
Just on purpose I made a [v0.7 fork](https://github.com/KlausC/MatrixDepot.jl) some time ago, which works for me. It should be identical to the required changes of this PR.

**Comment by pbouffard** [comment]
@KlausC thanks, actually I did see that, but maybe I should have raised an issue in your branch instead? I'd assumed that with this PR still open that the intent was still to merge it and adding another issue in the fork might be a distraction.

At any rate it's possible the issue is on my end but unless I'm using Pkg3 wrong (entirely possible!) I believe I am using your fork:

```
(v0.7) pkg> status
    Status `~/.julia/environments/v0.7/Project.toml`
...
  [b51810bb] MatrixDepot v0.6.0+ #master (https://github.com/KlausC/MatrixDepot.jl)
...
```

**Comment by KlausC** [comment]
@pbouffard I am a beginner in Pkg3and can't help there at all.
Actually I made the changes before I did even know about Pkg3.
On my installation, I have the package in a private subdir of "myjulia", which I access from julia setting
`push!(LOAD_PATH, joinpath(homedir(), "workspaces", "myjulia"))`.

You could check with git, if your copy has the last commits (from 7.April 2018 or later). There is the master branch with an unimportant warning and a branch `kc`, which has no syntax warnings for v0.7-beta2 (when `using MatrixDepot`).

I have no idea, which version julia is using. The official release (for v0.6) brings lots of warnings, and finally an error, but can be used, when I repeat the `using` statement.
Then I observe also the exception, when I call `matrixdepot("kahan")`.

**Comment by dwfmarchant** [comment]
Anything that can be done to help move this PR along?  What's blocking getting it merged?  Happy to help out if I can.

**Comment by weijianzhang** [comment]
Get it merged now! Many thanks!

**Pull request merged**
