### PR TITLE
Kc

### PR DESCRIPTION
**Pull request by KlausC**
This is a re-factoring of the existing code.
While the vintage API `matrixdepot(...)` is still supported it adds quite some new features.
It is presumed, that some of the items in https://github.com/JuliaMatrices/MatrixDepot.jl/issues/29 are covered as well.

1. `list(pattern)` delivers a list of full names matching the pattern. several variants of pattern are supported:
1.1 strings with or without shell pattern characters (`'*'`, `'?'`). Double star also matches `'/'`
1.2 regular expressions
1.3 integer matrix identifiers (as provided by the UFL collection) and ranges thereof
1.4 intersections of patterns (represented as a tuple of patterns)
1.5 unions of patterns (represented by an array of patterns)
1.6 group names - given as symbols, e.g. `:illcond` instead of `"ill-cond"`.
1.7 general predicate for `MatrixData` object, holding most important properties.
2. `info(pattern)` delivers information about all matrices matched by pattern as markdown object
3. `matrix(pattern, args...)` delivers a generated (with arguments) or loaded problem matrix
4.  `rhs(pattern)` delivers the b-side of the problem - if provided by the remote matrix.
5. `solution(pattern)` delivers the x-side of the problem - if provided as metadata.
6. `metareader(pattern, name)` delivers other metadata for remote problems.
7. `load(pattern)` loads all remote matrices matching the pattern from the dedicated servers.

The Matrixmarket-format reader has been completely re-written. It is now more reliable and faster than the previous approach, which used CHOLMOD.Sparse.

All retrieved data and metadata may be cached in memory on demand.
Information about the matrixmarket-format and the metadata are accessible using `data = mdopen(pattern)` or `data = MatrixDepot.mdata(pattern)`.
`mdclose(data)` removes all cached data.

### CODE REVIEW

**Comment by weijianzhang** [comment]
@andreasnoack I would prefer to keep the general `matrixdepot(...)` API, since using just one API to do everything is one of the key features of Matrix Depot. 

@KlausC great stuff! 
I'm in favour of not exporting the new API (load, matrix, rhs, list). They can be used as `MatrixDepot.load` etc.

**Comment by KlausC** [comment]
>  since using just one API to do everything is one of the key features of Matrix Depot.

Actually I proposed the new API, because I found it difficult to express the added features in the old one. I also think, having only one function as an and distinguishing functionality by different values (not even types) of the arguments is not a good `Julia`practice. I am thinking about type-stability and user-readability, at least.

**Comment by weijianzhang** [comment]
Ok, I see your point. Make sense. 

> `matrix(pattern, args...)` delivers a generated (with arguments) or loaded problem matrix

I would prefer we use`matrixdepot(pattern, args...)` so that users can still use the same API to generate matrices.

**Comment by KlausC** [comment]
@weijianzhang what my understanding of your request:
+ We use `matrixdepot(::Pattern, args...)` as the common way of creating matrices, locally generated ans well as remote ones. In the second case the `args` are not allowed.
In the case of remote examples, if the data files are not yet loaded, data load is started silently. That would in a way justify the name ("take the matrix from the remote or local depot").
+ The function `info` may be called also without arguments to deliver a markdown object containing formatted overview status info for the database.
+ other functions remain (exported)

**Comment by weijianzhang** [comment]
@KlausC Agreed on the first three points. For the last one

> other functions remain (exported)

I am a bit worried about function name conflict since `list`, `load`, `info` are quite general function names. Will this cause problem with other packages?

**Comment by KlausC** [comment]
I tried to adapt the API to @weijianzhang 's objections:
1. Access matrix using `A = matrixdepot(pattern, args...)`
2. Access all kinds of metadata:
2.1 `md = mdopen(pattern, args...)`
2.2 `A = md.A, b = md.b, x = md.x` to access matrix, rhs, solution (if available for `pattern`)
2.3 `x = metareader(md, name)` to obtain matrix -, vector- , or string data as stored in UFL
3. the functions `mdlist, mdinfo` are exported and replace the previous `list, info`
4. the functions `matrix, rhs, solution, load, info` are removed
4. the function `load` is not exported
5. a bunch of predicate functions is exported to allow convenient construction of patterns
example:  `mdlist(uf(2830) | kindhas(r"graph"i) & isloaded & ¬ispattern`

**Comment by KlausC** [comment]
@weijianzhang , @andreasnoack 
this PR is now complete as far as I can see.
I will still update `RELEASE.md`, `NEWS.md`, and `REQUIRES` if you give me a hint about the contents.

**Comment by andreasnoack** [comment]
@weijianzhang Are you okay with this?

**Comment by weijianzhang** [comment]
@KlausC @andreasnoack Sorry about my delay. Yes, looks great to me.

**Pull request merged**
