### PR TITLE
Get running on Julia 0.6

### PR DESCRIPTION
**Pull request by andreasnoack**
There are still some deprecations but FemtoClearner should be able to handle those.

@weijianzhang In case you don't have time to maintain the package anymore feel free to transfer it to JuliaMatrices and I can look into keeping it running.

### CODE REVIEW

**Comment by andreasnoack** [comment]
The tests pass on 0.6 but fails on master because of changes to how `workspace` works. I'm not sure `workspace` is completely solid, so maybe it is better to spawn new processes instead. In any case, I think fixing the package for Julia master should be a separate PR.

**Comment by weijianzhang** [comment]
Thanks @andreasnoack ! I am happy to transfer MatrixDepot to JuliaMatrices. A bit busy at the moment

**Comment by andreasnoack** [comment]
You should now be a member of JuliaMatrices and therefore be able to transfer it.

**Comment by weijianzhang** [comment]
Thanks

**Pull request merged**
