### PR TITLE
ignore cached db if not readable

### LINKED ISSUE #40: MatrixDepot does not initialize under julia1.4
EDIT: reason for the following misbehavior was an obsolete cached data file `db.data`.
WORKAROUND: remove `MatrixDepot/data/db.data` file. It will be re-created when module is initialized next time.

Under julia1.4 the module is not usable.
Under 1.2 no problems,  status for julia1.3 is unknown.

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0-DEV.595 (2019-12-17)
 _/ |\__'_|_|_|\__'_|  |  krc/awmax/5fc8a05be4* (fork: 3 commits, 17 days)
|__/                   |

julia> using MatrixDepot
[ Info: Precompiling MatrixDepot [top-level]
include group.jl for user defined matrix generators
verify download of index files...
┌ Warning: exception during initialization: 'KeyError(MatrixDepot [b51810bb-c9f3-55da-ae3c-350fc1fbce05])'
└ @ MatrixDepot ~/.julia/dev/MatrixDepot/src/MatrixDepot.jl:135

julia> MatrixDepot.DATA_DIR
"/home/crusius/.julia/dev/MatrixDepot/data"

julia> MatrixDepot.mdinfo()
ERROR: MatrixDepot.DataError("no matrix according to baart found")

julia> MatrixDepot.init()
include group.jl for user defined matrix generators
verify download of index files...
ERROR: KeyError: key MatrixDepot [b51810bb-c9f3-55da-ae3c-350fc1fbce05] not found
Stacktrace:
 [1] getindex at ./dict.jl:477 [inlined]
 [2] root_module at ./loading.jl:960 [inlined]
 [3] deserialize_module(::Serialization.Serializer{IOStream}) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:912
 [4] handle_deserialize(::Serialization.Serializer{IOStream}, ::Int32) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:812
 [5] deserialize(::Serialization.Serializer{IOStream}) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:735
 [6] deserialize_datatype(::Serialization.Serializer{IOStream}, ::Bool) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:1210
 [7] handle_deserialize(::Serialization.Serializer{IOStream}, ::Int32) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:788
 [8] deserialize(::Serialization.Serializer{IOStream}) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:735
 [9] handle_deserialize(::Serialization.Serializer{IOStream}, ::Int32) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:795
 [10] deserialize(::Serialization.Serializer{IOStream}) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:735
 [11] handle_deserialize(::Serialization.Serializer{IOStream}, ::Int32) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:838
 [12] deserialize(::Serialization.Serializer{IOStream}) at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:735
 [13] deserialize at /home/julia/julia/usr/share/julia/stdlib/v1.4/Serialization/src/Serialization.jl:722 [inlined]
 [14] (::MatrixDepot.var"#100#101"{MatrixDepot.MatrixDatabase})(::IOStream) at /home/crusius/.julia/dev/MatrixDepot/src/download.jl:101
 [15] open(::MatrixDepot.var"#100#101"{MatrixDepot.MatrixDatabase}, ::String, ::Vararg{String,N} where N; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:298
 [16] open at ./io.jl:296 [inlined]
 [17] readdb at /home/crusius/.julia/dev/MatrixDepot/src/download.jl:100 [inlined]
 [18] downloadindices(::MatrixDepot.MatrixDatabase; ignoredb::Bool) at /home/crusius/.julia/dev/MatrixDepot/src/download.jl:125
 [19] init(; ignoredb::Bool) at /home/crusius/.julia/dev/MatrixDepot/src/MatrixDepot.jl:128
 [20] init() at /home/crusius/.julia/dev/MatrixDepot/src/MatrixDepot.jl:102
 [21] top-level scope at REPL[4]:1

julia> 
```

### PR DESCRIPTION
**Pull request by KlausC**
Fixes #40. 
Also add `Project.toml`.

### CODE REVIEW

**Comment by KlausC** [comment]
Failing tests because of missing network connectivity on Linux nodes of travis.

**Comment by andreasnoack** [comment]
Could you please rebase this one?

**Comment by KlausC** [comment]
This is a bug fix, could it be merged?

**Comment by andreasnoack** [comment]
I think it would be fair with a little more explanation of a ~40k lines diff. E.g. is the role of data/uf_matrices.html and why is `MAT.jl` added as dependency?

**Comment by KlausC** [comment]
Sorry, the last 2 commits should not go there. They belong to the current WIP-PR and will be explained.
For the moment, please ignore this until I have undone the unwanted commits.

**Comment by KlausC** [comment]
This PR is retired - I could not mange to revert the necessary commits. Added bug fix will be included in upcoming PR.

**Pull request closed without merging**
